// <auto-generated />
using System;
using LAUCHA.infrastructure.persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAUCHA.infrastructure.Migrations
{
    [DbContext(typeof(LiquidacionesDbContext))]
    [Migration("20260603104117_CambiosEnElAcuerdo")]
    partial class CambiosEnElAcuerdo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.Acuerdo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("DniEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("DniEmpleado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Sueldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoSueldo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorSueldoOJornal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo");

                    b.HasIndex("DniEmpleado");

                    b.ToTable("Acuerdos", (string)null);
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.RetencionAcuerdo", b =>
                {
                    b.Property<string>("CodigoRetencion")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CodigoAcuerdo")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsPorcentual")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PrimeraQuincena")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Unidades")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CodigoRetencion", "CodigoAcuerdo");

                    b.HasIndex("CodigoAcuerdo");

                    b.ToTable("RetencionAcuerdo");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.Credito", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(95)");

                    b.Property<int>("CantidadCuotas")
                        .HasColumnType("int");

                    b.Property<string>("CodigoLiquidacionAcreditacion")
                        .HasColumnType("varchar(95)");

                    b.Property<DateTime>("Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DniEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModoPago")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoDevolver")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontoPrestado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoLiquidacionAcreditacion");

                    b.HasIndex("DniEmpleado");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.CuotaCredito", b =>
                {
                    b.Property<int>("Nro")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<string>("CodigoCredito")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("AnioDebitar")
                        .HasColumnType("int");

                    b.Property<string>("CodigoLiquidacion")
                        .HasColumnType("varchar(95)");

                    b.Property<DateTime>("Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MesDebitar")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuincenaDebitar")
                        .HasColumnType("int");

                    b.HasKey("Nro", "CodigoCredito");

                    b.HasIndex("CodigoCredito");

                    b.HasIndex("CodigoLiquidacion");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Empleados.Empleado", b =>
                {
                    b.Property<string>("Dni")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Dni");

                    b.HasIndex("Cuil")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.ItemLiquidacion", b =>
                {
                    b.Property<string>("CodigoLiquidacion")
                        .HasColumnType("varchar(95)");

                    b.Property<int>("NroItem")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsEnBlanco")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsIncremento")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<bool>("generadoPorUsuario")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CodigoLiquidacion", "NroItem");

                    b.ToTable("ItemLiquidacion");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(95)");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("CodigoAcuerdo")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DniEmpleado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSello")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Quincena")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoAcuerdo");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Pagos.Pago", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("EstadoContable")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LiquidacionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Modo")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenciaContabilidad")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.RetencionesCatalogo.CatalogoRetencion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsPorcentual")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PrimeraQuincena")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Unidades")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Codigo");

                    b.ToTable("CatalogoRetenciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Contrato.Adicional", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CodigoAcuerdo")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsEnBlanco")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsPorcentual")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoAcuerdo");

                    b.ToTable("Adicionales");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.Acuerdo", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Empleados.Empleado", "Empleado")
                        .WithMany("Contratos")
                        .HasForeignKey("DniEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Acuerdos_Empleados_DniEmpleado");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.RetencionAcuerdo", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Acuerdos.Acuerdo", null)
                        .WithMany("Retenciones")
                        .HasForeignKey("CodigoAcuerdo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.Entities.RetencionesCatalogo.CatalogoRetencion", null)
                        .WithMany()
                        .HasForeignKey("CodigoRetencion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.Credito", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", null)
                        .WithMany()
                        .HasForeignKey("CodigoLiquidacionAcreditacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LAUCHA.domain.Entities.Empleados.Empleado", null)
                        .WithMany()
                        .HasForeignKey("DniEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.CuotaCredito", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Creditos.Credito", null)
                        .WithMany("Cuotas")
                        .HasForeignKey("CodigoCredito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", null)
                        .WithMany()
                        .HasForeignKey("CodigoLiquidacion")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.ItemLiquidacion", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", null)
                        .WithMany("Items")
                        .HasForeignKey("CodigoLiquidacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Acuerdos.Acuerdo", "Acuerdo")
                        .WithMany()
                        .HasForeignKey("CodigoAcuerdo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acuerdo");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Pagos.Pago", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", null)
                        .WithMany("Pagos")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Contrato.Adicional", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Acuerdos.Acuerdo", null)
                        .WithMany("Adicionales")
                        .HasForeignKey("CodigoAcuerdo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.Acuerdo", b =>
                {
                    b.Navigation("Adicionales");

                    b.Navigation("Retenciones");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.Credito", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Empleados.Empleado", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
