// <auto-generated />
using System;
using LAUCHA.infrastructure.persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAUCHA.infrastructure.Migrations
{
    [DbContext(typeof(LiquidacionesDbContext))]
    [Migration("20260116151315_DescarteDiasEspeciales")]
    partial class DescarteDiasEspeciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.Acuerdo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DniEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DniEmpleado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Sueldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoSueldo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBlanco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo");

                    b.HasIndex("DniEmpleado");

                    b.ToTable("Acuerdos", (string)null);
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.RetencionAcuerdo", b =>
                {
                    b.Property<string>("CodigoRetencion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoAcuerdo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsPorcentual")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PrimeraQuincena")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Unidades")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CodigoRetencion", "CodigoAcuerdo");

                    b.HasIndex("CodigoAcuerdo");

                    b.ToTable("RetencionAcuerdo");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.Credito", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CantidadCuotas")
                        .HasColumnType("int");

                    b.Property<string>("CodigoLiquidacionAcreditacion")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ConceptoNumeroConcepto")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CuentaNumeroCuenta")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DniEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModoPago")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoDevolver")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MontoPrestado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoLiquidacionAcreditacion");

                    b.HasIndex("ConceptoNumeroConcepto");

                    b.HasIndex("CuentaNumeroCuenta");

                    b.HasIndex("DniEmpleado");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.CuotaCredito", b =>
                {
                    b.Property<int>("Nro")
                        .HasColumnType("int");

                    b.Property<string>("CodigoCredito")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AnioDebitar")
                        .HasColumnType("int");

                    b.Property<string>("CodigoLiquidacion")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MesDebitar")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuincenaDebitar")
                        .HasColumnType("int");

                    b.HasKey("Nro", "CodigoCredito");

                    b.HasIndex("CodigoCredito");

                    b.HasIndex("CodigoLiquidacion");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Empleados.Empleado", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Dni");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.ItemLiquidacion", b =>
                {
                    b.Property<string>("CodigoLiquidacion")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NroItem")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsAutomatico")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsEnBlanco")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsIncremento")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("CodigoLiquidacion", "NroItem");

                    b.ToTable("ItemLiquidacion");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("CodigoAcuerdo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoLiquidacionGeneral")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DniEmpleado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaLiquidacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSello")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Quincena")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoAcuerdo");

                    b.HasIndex("CodigoLiquidacionGeneral");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.RetencionesCatalogo.CatalogoRetencion", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsPorcentual")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PrimeraQuincena")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Unidades")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Codigo");

                    b.ToTable("CatalogoRetenciones");

                    b.HasData(
                        new
                        {
                            Codigo = "0900",
                            Concepto = "Jubilacion",
                            EsPorcentual = true,
                            PrimeraQuincena = false,
                            Unidades = 11m
                        },
                        new
                        {
                            Codigo = "0905",
                            Concepto = "Ley 19032",
                            EsPorcentual = true,
                            PrimeraQuincena = false,
                            Unidades = 3m
                        },
                        new
                        {
                            Codigo = "0940",
                            Concepto = "Seguro y Sepelio",
                            EsPorcentual = false,
                            PrimeraQuincena = true,
                            Unidades = 2300m
                        },
                        new
                        {
                            Codigo = "0910",
                            Concepto = "Obra Social",
                            EsPorcentual = true,
                            PrimeraQuincena = false,
                            Unidades = 3m
                        },
                        new
                        {
                            Codigo = "0920",
                            Concepto = "Aporte Sindical Obligatorio",
                            EsPorcentual = true,
                            PrimeraQuincena = false,
                            Unidades = 2.5m
                        });
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Concepto", b =>
                {
                    b.Property<int>("NumeroConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NombreConcepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NumeroConcepto");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Contrato.Adicional", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoAcuerdo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsEnBlanco")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsPorcentual")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoAcuerdo");

                    b.ToTable("Adicionales");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Cuenta", b =>
                {
                    b.Property<string>("NumeroCuenta")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DniEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EstadoCuenta")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("NumeroCuenta");

                    b.HasIndex("DniEmpleado")
                        .IsUnique();

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Descuento", b =>
                {
                    b.Property<string>("CodigoDescuento")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("NumeroConcepto")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoDescuento");

                    b.HasIndex("NumeroConcepto");

                    b.HasIndex("NumeroCuenta");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.DescuentoPorLiquidacionPersonal", b =>
                {
                    b.Property<string>("CodigoDescuento")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoLiquidacionPersonal")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoDescuento", "CodigoLiquidacionPersonal");

                    b.HasIndex("CodigoLiquidacionPersonal");

                    b.ToTable("DescuentosPorLiquidaciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.LiquidacionGeneral", b =>
                {
                    b.Property<string>("CodigoLiquidacionGeneral")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FinPeriodo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InicioPeriodo")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalDescuentos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalRemuneracion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalRetencion")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CodigoLiquidacionGeneral");

                    b.ToTable("LiquidacionesGenerales");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.NoRemuneracion", b =>
                {
                    b.Property<string>("CodigoNoRemuneracion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoNoRemuneracion");

                    b.HasIndex("NumeroCuenta");

                    b.ToTable("NoRemuneraciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.NoRemuneracionPorLiquidacionPersonal", b =>
                {
                    b.Property<string>("CodigoNoRemuneracion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoLiquidacionPersonal")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoNoRemuneracion", "CodigoLiquidacionPersonal");

                    b.HasIndex("CodigoLiquidacionPersonal");

                    b.ToTable("NoRemuneracionesPorLiquidaciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.PagoLiquidacion", b =>
                {
                    b.Property<int>("CodigoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoLiquidacion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CodigoPago");

                    b.HasIndex("CodigoLiquidacion");

                    b.ToTable("PagosLiquidaciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Remuneracion", b =>
                {
                    b.Property<string>("CodigoRemuneracion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsBlanco")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoRemuneracion");

                    b.HasIndex("NumeroCuenta");

                    b.ToTable("Remuneraciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.RemuneracionPorLiquidacionPersonal", b =>
                {
                    b.Property<string>("CodigoRemuneracion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoLiquidacionPersonal")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoRemuneracion", "CodigoLiquidacionPersonal");

                    b.HasIndex("CodigoLiquidacionPersonal");

                    b.ToTable("RemuneracionesPorLiquidaciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.RetencionOLD", b =>
                {
                    b.Property<string>("CodigoRetencion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoRetencion");

                    b.HasIndex("NumeroCuenta");

                    b.ToTable("Retenciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.RetencionPorLiquidacionPersonal", b =>
                {
                    b.Property<string>("CodigoRetencion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoLiquidacionPersonal")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoRetencion", "CodigoLiquidacionPersonal");

                    b.HasIndex("CodigoLiquidacionPersonal");

                    b.ToTable("RetencionesPorLiquidaciones");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.Acuerdo", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Empleados.Empleado", "Empleado")
                        .WithMany("Contratos")
                        .HasForeignKey("DniEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Acuerdos_Empleados_DniEmpleado");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.RetencionAcuerdo", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Acuerdos.Acuerdo", null)
                        .WithMany("Retenciones")
                        .HasForeignKey("CodigoAcuerdo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.Entities.RetencionesCatalogo.CatalogoRetencion", null)
                        .WithMany()
                        .HasForeignKey("CodigoRetencion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.Credito", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", null)
                        .WithMany()
                        .HasForeignKey("CodigoLiquidacionAcreditacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LAUCHA.domain.entities.Concepto", null)
                        .WithMany("Creditos")
                        .HasForeignKey("ConceptoNumeroConcepto");

                    b.HasOne("LAUCHA.domain.entities.Cuenta", null)
                        .WithMany("Creditos")
                        .HasForeignKey("CuentaNumeroCuenta");

                    b.HasOne("LAUCHA.domain.Entities.Empleados.Empleado", null)
                        .WithMany()
                        .HasForeignKey("DniEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.CuotaCredito", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Creditos.Credito", null)
                        .WithMany("Cuotas")
                        .HasForeignKey("CodigoCredito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", null)
                        .WithMany()
                        .HasForeignKey("CodigoLiquidacion")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.ItemLiquidacion", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", null)
                        .WithMany("Items")
                        .HasForeignKey("CodigoLiquidacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Acuerdos.Acuerdo", "Acuerdo")
                        .WithMany()
                        .HasForeignKey("CodigoAcuerdo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.entities.LiquidacionGeneral", "LiquidacionGeneral")
                        .WithMany("LiquidacionesPersonales")
                        .HasForeignKey("CodigoLiquidacionGeneral");

                    b.Navigation("Acuerdo");

                    b.Navigation("LiquidacionGeneral");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Contrato.Adicional", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Acuerdos.Acuerdo", null)
                        .WithMany("Adicionales")
                        .HasForeignKey("CodigoAcuerdo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Cuenta", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Empleados.Empleado", "Empleado")
                        .WithOne("Cuenta")
                        .HasForeignKey("LAUCHA.domain.entities.Cuenta", "DniEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Descuento", b =>
                {
                    b.HasOne("LAUCHA.domain.entities.Concepto", "Concepto")
                        .WithMany("Descuentos")
                        .HasForeignKey("NumeroConcepto");

                    b.HasOne("LAUCHA.domain.entities.Cuenta", "Cuenta")
                        .WithMany("Descuentos")
                        .HasForeignKey("NumeroCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concepto");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.DescuentoPorLiquidacionPersonal", b =>
                {
                    b.HasOne("LAUCHA.domain.entities.Descuento", "Descuento")
                        .WithMany("DescuentoPorLiquidacionPersonales")
                        .HasForeignKey("CodigoDescuento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", "LiquidacionPersonal")
                        .WithMany("DescuentoPorLiquidacionPersonales")
                        .HasForeignKey("CodigoLiquidacionPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descuento");

                    b.Navigation("LiquidacionPersonal");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.NoRemuneracion", b =>
                {
                    b.HasOne("LAUCHA.domain.entities.Cuenta", "Cuenta")
                        .WithMany("NoRemuneraciones")
                        .HasForeignKey("NumeroCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.NoRemuneracionPorLiquidacionPersonal", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", "LiquidacionPersonal")
                        .WithMany("NoRemuneracionesPorLiquidaciones")
                        .HasForeignKey("CodigoLiquidacionPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.entities.NoRemuneracion", "NoRemuneracion")
                        .WithMany("NoRemuneracionesPorLiquidaciones")
                        .HasForeignKey("CodigoNoRemuneracion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiquidacionPersonal");

                    b.Navigation("NoRemuneracion");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.PagoLiquidacion", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", "Liquidacion")
                        .WithMany("PagosLiquidacion")
                        .HasForeignKey("CodigoLiquidacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Remuneracion", b =>
                {
                    b.HasOne("LAUCHA.domain.entities.Cuenta", "Cuenta")
                        .WithMany("Remuneraciones")
                        .HasForeignKey("NumeroCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.RemuneracionPorLiquidacionPersonal", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", "LiquidacionPersonal")
                        .WithMany("RemuneracionPorLiquidacionPersonales")
                        .HasForeignKey("CodigoLiquidacionPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.entities.Remuneracion", "Remuneracion")
                        .WithMany("RemuneracionPorLiquidacionPersonales")
                        .HasForeignKey("CodigoRemuneracion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiquidacionPersonal");

                    b.Navigation("Remuneracion");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.RetencionOLD", b =>
                {
                    b.HasOne("LAUCHA.domain.entities.Cuenta", "Cuenta")
                        .WithMany("Retenciones")
                        .HasForeignKey("NumeroCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.RetencionPorLiquidacionPersonal", b =>
                {
                    b.HasOne("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", "LiquidacionPersonal")
                        .WithMany("RetencionPorLiquidacionPersonales")
                        .HasForeignKey("CodigoLiquidacionPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAUCHA.domain.entities.RetencionOLD", "Retencion")
                        .WithMany("RetencionPorLiquidacionPersonales")
                        .HasForeignKey("CodigoRetencion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiquidacionPersonal");

                    b.Navigation("Retencion");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Acuerdos.Acuerdo", b =>
                {
                    b.Navigation("Adicionales");

                    b.Navigation("Retenciones");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Creditos.Credito", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Empleados.Empleado", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Cuenta")
                        .IsRequired();
                });

            modelBuilder.Entity("LAUCHA.domain.Entities.Liquidaciones.Liquidacion", b =>
                {
                    b.Navigation("DescuentoPorLiquidacionPersonales");

                    b.Navigation("Items");

                    b.Navigation("NoRemuneracionesPorLiquidaciones");

                    b.Navigation("PagosLiquidacion");

                    b.Navigation("RemuneracionPorLiquidacionPersonales");

                    b.Navigation("RetencionPorLiquidacionPersonales");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Concepto", b =>
                {
                    b.Navigation("Creditos");

                    b.Navigation("Descuentos");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Cuenta", b =>
                {
                    b.Navigation("Creditos");

                    b.Navigation("Descuentos");

                    b.Navigation("NoRemuneraciones");

                    b.Navigation("Remuneraciones");

                    b.Navigation("Retenciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Descuento", b =>
                {
                    b.Navigation("DescuentoPorLiquidacionPersonales");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.LiquidacionGeneral", b =>
                {
                    b.Navigation("LiquidacionesPersonales");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.NoRemuneracion", b =>
                {
                    b.Navigation("NoRemuneracionesPorLiquidaciones");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.Remuneracion", b =>
                {
                    b.Navigation("RemuneracionPorLiquidacionPersonales");
                });

            modelBuilder.Entity("LAUCHA.domain.entities.RetencionOLD", b =>
                {
                    b.Navigation("RetencionPorLiquidacionPersonales");
                });
#pragma warning restore 612, 618
        }
    }
}
